
# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Code generated by Microsoft (R) AutoRest Code Generator.Changes may cause incorrect behavior and will be lost if the code
# is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for DataShareSourceUpdate.
.Description
Create an in-memory object for DataShareSourceUpdate.

.Outputs
Microsoft.Azure.PowerShell.Cmdlets.Storage.Models.DataShareSourceUpdate
.Link
https://learn.microsoft.com/powershell/module/Az.Storage/new-azstoragedatasharesourceupdateobject
#>
function New-AzStorageDataShareSourceUpdateObject {
    [Microsoft.Azure.PowerShell.Cmdlets.Storage.ModelCmdletAttribute()]
    [OutputType('Microsoft.Azure.PowerShell.Cmdlets.Storage.Models.DataShareSourceUpdate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(HelpMessage="Details for how to authenticate to the backing data store.")]
        [Microsoft.Azure.PowerShell.Cmdlets.Storage.Models.IStorageConnectorAuthPropertiesUpdate]
        $AuthProperty
    )

    process {
        $Object = [Microsoft.Azure.PowerShell.Cmdlets.Storage.Models.DataShareSourceUpdate]::New()

        if ($PSBoundParameters.ContainsKey('AuthProperty')) {
            $Object.AuthProperty = $AuthProperty
        }
        return $Object
    }
}

