
# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Code generated by Microsoft (R) AutoRest Code Generator.Changes may cause incorrect behavior and will be lost if the code
# is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for StorageDataShareAccessPolicy.
.Description
Create an in-memory object for StorageDataShareAccessPolicy.

.Outputs
Microsoft.Azure.PowerShell.Cmdlets.Storage.Models.StorageDataShareAccessPolicy
.Link
https://learn.microsoft.com/powershell/module/Az.Storage/new-azstoragedatashareaccesspolicyobject
#>
function New-AzStorageDataShareAccessPolicyObject {
    [Microsoft.Azure.PowerShell.Cmdlets.Storage.ModelCmdletAttribute()]
    [OutputType('Microsoft.Azure.PowerShell.Cmdlets.Storage.Models.StorageDataShareAccessPolicy')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory, HelpMessage="Allowed permissions. Currently, only supported value is Read.")]
        [Microsoft.Azure.PowerShell.Cmdlets.Storage.PSArgumentCompleterAttribute("None", "Read")]
        [string]
        $Permission,
        [Parameter(Mandatory, HelpMessage="The AAD principal ID of the Managed Identity.")]
        [string]
        $PrincipalId,
        [Parameter(Mandatory, HelpMessage="The AAD tenant ID of the Managed Identity.")]
        [string]
        $TenantId
    )

    process {
        $Object = [Microsoft.Azure.PowerShell.Cmdlets.Storage.Models.StorageDataShareAccessPolicy]::New()

        if ($PSBoundParameters.ContainsKey('Permission')) {
            $Object.Permission = $Permission
        }
        if ($PSBoundParameters.ContainsKey('PrincipalId')) {
            $Object.PrincipalId = $PrincipalId
        }
        if ($PSBoundParameters.ContainsKey('TenantId')) {
            $Object.TenantId = $TenantId
        }
        return $Object
    }
}

