
# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Code generated by Microsoft (R) AutoRest Code Generator.Changes may cause incorrect behavior and will be lost if the code
# is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for StorageDataShareAsset.
.Description
Create an in-memory object for StorageDataShareAsset.

.Outputs
Microsoft.Azure.PowerShell.Cmdlets.Storage.Models.StorageDataShareAsset
.Link
https://learn.microsoft.com/powershell/module/Az.Storage/new-azstoragedatashareassetobject
#>
function New-AzStorageDataShareAssetObject {
    [Microsoft.Azure.PowerShell.Cmdlets.Storage.ModelCmdletAttribute()]
    [OutputType('Microsoft.Azure.PowerShell.Cmdlets.Storage.Models.StorageDataShareAsset')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory, HelpMessage="Source Path to be shared. It can be a folder or a blob.
        The asset path should contain container name followed by path within the container, e.g. /container1/logs/external.")]
        [string]
        $AssetPath,
        [Parameter(Mandatory, HelpMessage="Consumer visible name of the original path.")]
        [string]
        $DisplayName
    )

    process {
        $Object = [Microsoft.Azure.PowerShell.Cmdlets.Storage.Models.StorageDataShareAsset]::New()

        if ($PSBoundParameters.ContainsKey('AssetPath')) {
            $Object.AssetPath = $AssetPath
        }
        if ($PSBoundParameters.ContainsKey('DisplayName')) {
            $Object.DisplayName = $DisplayName
        }
        return $Object
    }
}

